#!/bin/bash

echo "📋 Step-by-Step Guide to Add New SKUs"
echo "======================================"
echo ""
echo "Option 1: Azure Portal (RECOMMENDED)"
echo "-------------------------------------"
echo "1. Open: https://portal.azure.com"
echo "2. Navigate to: PostgreSQL → itc-warehouse-db-2025 → Query editor"
echo "3. Copy the SQL from: database/add-new-skus.sql"
echo "4. Paste and Execute"
echo "5. Then run: curl -X POST https://itc-warehouse-app-2025-c8hgg5deeagae5dj.centralindia-01.azurewebsites.net/api/admin/sync-active-skus"
echo ""
echo "Option 2: Wait for API Deployment"
echo "----------------------------------"
echo "Wait 2-3 more minutes, then run:"
echo "  node upload-new-skus.js"
echo "  curl -X POST https://itc-warehouse-app-2025-c8hgg5deeagae5dj.centralindia-01.azurewebsites.net/api/admin/sync-active-skus"
echo ""
echo "======================================"
echo "After this, refresh the Incoming page to see new SKUs!"
